### ISSUE TITLE
Freezes using when opening files

### ISSUE THREAD

**Issue by Bertus-W** [lotabout/skim.vim#1]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, I tried using Skim because FZF broke. But I think the problem is the plugin. The problem is that the editor freezes ik you open a file using `:Files`. I am posting this issue here because the FZF devs are not responding.

**Comment by lotabout** [comment]
@Catman155 Sorry for late reply. Let me confirm:

1. Does the problem happens only in FZF or in both Skim and FZF?
2. If possible, please share the information of the Linux version and neovim version that you are using.

**Comment by Bertus-W** [comment]
Hi, thank you for your response. This issue appears to be happening in both FZF and Skim. I suspect it's an issue with the vim plugin. I'm running neovim version: 
NVIM v0.2.3-1-gd6f9d1df0
Build type: RelWithDebInfo
LuaJIT 2.0.5

And I'm running this version of Linux: Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**Comment by lotabout** [comment]
@Catman155 Can't help to notice that you are using NVIM v0.2.3 which is not the "official" list. Could you please try NVIM v0.2.2 please? I'd like to confirm whether it could be a problem of nvim.

ref: [nvim releases](https://github.com/neovim/neovim/releases)

**Comment by Cmdr3nder** [comment]
I also ran into this issue when trying to get `:SK` working today. I happened to be running an old version of NVIM from around the same era as NVIM v0.2.3. I solved the freezing issue by updating to NVIM v0.3.4.
