### ISSUE TITLE
Home key does not work but End key works

### ISSUE THREAD

**Issue by JokerQyou** [lotabout/skim.vim#5]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I noticed when typing in `:SK` prompt, the `Home` key does not work, however the `End` key works. That is, I cannot use `Home` key to quickly place the cursor at the beginning of my input.

When in `:FZF` prompt they both work fine.

Vim version is `8.0` with patch `1-1453`, but I don't think it's related since fzf works.

**Comment by lotabout** [comment]
It's a problem of skim, fixed in the above MR.
