### ISSUE TITLE
Rename autoload/fzf to autoload/skim

### ISSUE THREAD

**Issue by liuchengxu** [lotabout/skim.vim#6]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

I was trying to integrate [skim.vim](https://github.com/lotabout/skim.vim) into [vista.vim](https://github.com/liuchengxu/vista.vim), see also https://github.com/liuchengxu/vista.vim/issues/129, only to find that skim.vim still uses the original `autoload/fzf/*` instead of `autoload/skim/*`, which could lead to the conflicts with fzf.vim. People will run into some issues if using fzf.vim and skim.vim at the same time.

I notice that https://github.com/lotabout/skim/blob/master/plugin/skim.vim has been renamed, are there any special reasons for not doing the same thing for skim.vim?

**Comment by lotabout** [comment]
@liuchengxu The initial intention was to reduce the maintenance cost. Keeping the names intact will keep it simple to track fzf.vim's latest changes. I'll reconsider.

**Comment by polyzen** [comment]
OTOH having both fzf and skim installed seems counterproductive, but I see how this could impede testing.

**Comment by liuchengxu** [comment]
Closing this as the skim support has been added in vista.vim (https://github.com/liuchengxu/vista.vim/pull/147). For the basic integration of skim, it's enough to just install [skim](https://github.com/lotabout/skim), then there is no conflicts with fzf.vim.
